// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyztV3KJc8R4-gPzfy6EV59gV2-WboBao',
    appId: '1:862634440640:web:a79d21c5d2949e41c7ba25',
    messagingSenderId: '862634440640',
    projectId: 'clipboard-f2f4f',
    authDomain: 'clipboard-f2f4f.firebaseapp.com',
    storageBucket: 'clipboard-f2f4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIDQ1LfdQW1giVv3J0YJVfNWdJcy7Il1I',
    appId: '1:862634440640:android:25b767f18fe68e17c7ba25',
    messagingSenderId: '862634440640',
    projectId: 'clipboard-f2f4f',
    storageBucket: 'clipboard-f2f4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfxKLRpHdv3Xq7KUT52Gp_cV3Yo3eDcmY',
    appId: '1:862634440640:ios:c248c6f111361ee0c7ba25',
    messagingSenderId: '862634440640',
    projectId: 'clipboard-f2f4f',
    storageBucket: 'clipboard-f2f4f.appspot.com',
    iosBundleId: 'com.allysoftsolutions.clipboardApp',
  );
}
